[package]
name = "connected-components"
version = "0.1.0"
authors = ["Bastian Meyer <bastian@bastianmeyer.eu>"]

[dependencies]
differential-dataflow = { git = "https://github.com/frankmcsherry/differential-dataflow.git" }
rand = "0.3.0"
timely = "0.1.0"
